Allow connecting by non-localhost IP, also from external machines

diff --git a/bin/initd b/bin/initd
--- a/bin/initd
+++ b/bin/initd
@@ -8,7 +8,7 @@
 # Description:    Wolfpack iptables configuration
 ### END INIT INFO
 
-set +e   # Don't exit on error status
+set -e # Exit on error status
 
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 # DAEMON=/usr/local/bin/prax
@@ -17,18 +17,27 @@ DESC="Wolfpack iptables configuration"
 HTTP_PORT=30666
 HTTPS_PORT=30667
 
+remove_rules_for_chain() {
+  RULE_NUMS=`iptables -t nat -L $1 --line-numbers -n | egrep "($HTTP_PORT|$HTTPS_PORT)" | awk '{a[i++]=$0} END { for (j=i-1; j>=0;) print a[j--] }' | awk -F " " '{ print $1 }'`
+  for RULE_NUM in $RULE_NUMS ; do
+    iptables -t nat -D $1 $RULE_NUM
+  done
+}
+
 case "$1" in
   start)
     if [ `iptables -t nat -L -n | egrep "($HTTP_PORT|$HTTPS_PORT)" | wc -l` -eq 0 ] ; then
-      iptables -t nat -A OUTPUT -p tcp -d 127.0.0.1 --dport 80  -j REDIRECT --to-ports $HTTP_PORT
-      iptables -t nat -A OUTPUT -p tcp -d 127.0.0.1 --dport 443 -j REDIRECT --to-ports $HTTPS_PORT
+      # for remote connections
+      iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports $HTTP_PORT
+      iptables -t nat -I PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports $HTTPS_PORT
+      # for local connections
+      iptables -t nat -A OUTPUT -p tcp -o lo --dport 80  -j REDIRECT --to-ports $HTTP_PORT
+      iptables -t nat -A OUTPUT -p tcp -o lo --dport 443 -j REDIRECT --to-ports $HTTPS_PORT
     fi
     ;;
   stop)
-    RULE_NUMS=`iptables -t nat -L --line-numbers -n | egrep "($HTTP_PORT|$HTTPS_PORT)" | awk '{a[i++]=$0} END { for (j=i-1; j>=0;) print a[j--] }' | awk -F " " '{ print $1 }'`
-    for RULE_NUM in $RULE_NUMS ; do
-      iptables -t nat -D OUTPUT $RULE_NUM
-    done
+    remove_rules_for_chain 'OUTPUT'
+    remove_rules_for_chain 'PREROUTING'
     ;;
   restart)
     $0 stop
